#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Mar 30, 2024 01:20:14 AM CET  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path
import time

_location = os.path.dirname(__file__)

import app_run_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black'
_tabfg2 = 'white'
_bgmode = 'light'
_tabbg1 = '#d9d9d9'
_tabbg2 = 'gray40'

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("720x450+380+125")
        top.attributes('-fullscreen', True)
        #top.minsize(120, 1)
        #top.maxsize(1540, 845)
        top.resizable(0,  0)
        top.title("Tests application")
        top.configure(background="#ED1C24")
        #top.configure(highlightbackground="#d9d9d9")
        #top.configure(highlightcolor="#000000")

        self.top = top

        self.Label0 = tk.Label(self.top)
        self.Label0.place(x=120, y=40, height=71, width=550)
        self.Label0.configure(activebackground="#ED1C24")
        self.Label0.configure(activeforeground="black")
        self.Label0.configure(anchor='w')
        self.Label0.configure(background="#ED1C24")
        self.Label0.configure(font="-family {Orator Std} -size 40")
        self.Label0.configure(foreground="#FFFFFF")
        self.Label0.configure(relief="flat")
        self.Label0.configure(text='''Farming Mars 2024''')

        self.Label1 = tk.Label(self.top)
        self.Label1.place(x=270, y=290, height=71, width=171)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Fixedsys} -size 67")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(relief="solid")
        self.Label1.configure(text='''0''')

        self.bt_bleu = tk.Button(self.top)
        self.bt_bleu.place(x=90, y=140, height=120, width=200)
        self.bt_bleu.configure(relief=FLAT)
        self.bt_bleu.configure(activebackground="#005B8C")
        self.bt_bleu.configure(background="#005B8C")
        self.bt_bleu.configure(command=app_run_support.bleu)
        self.bt_bleu.configure(highlightbackground="#005B8C")
        self.bt_bleu.configure(highlightcolor="#005B8C")

        self.bt_jaune = tk.Button(self.top)
        self.bt_jaune.place(x=410, y=140, height=120, width=200)
        self.bt_jaune.configure(relief=FLAT)
        self.bt_jaune.configure(activebackground="#FFBF00")
        self.bt_jaune.configure(background="#FFBF00")
        self.bt_jaune.configure(command=app_run_support.jaune)
        self.bt_jaune.configure(highlightbackground="#FFBF00")
        self.bt_jaune.configure(highlightcolor="#FFBF00")

        self._is_timer_ON = tk.IntVar()
        self.timer_btn = tk.Checkbutton(self.top)
        self.timer_btn.pack()
        self.timer_btn.place(x=510, y=300, height=50, width=120)
        self.timer_btn.configure(text="Timer")
        self.timer_btn.configure(variable=self._is_timer_ON)
        self.timer_btn.configure(onvalue=1, offvalue=0)
        self.timer_btn.configure(background="#C23B22")
        self.timer_btn.configure(font="-family {Orator Std} -size 14 -weight bold")
        self.timer_btn.configure(highlightbackground="#C23B22")
        self.timer_btn.configure(highlightcolor="#C23B22")

        self._strat = tk.IntVar()
        self.strategy = 1  # Stratégie complète de base
        self.strat_btn1 = tk.Radiobutton(self.top)
        self.strat_btn1.pack()
        self.strat_btn1.place(x=30, y=300, height=50, width=200)
        self.strat_btn1.configure(text="STRATEGY_1")
        self.strat_btn1.configure(variable=self._strat)
        self.strat_btn1.configure(value=1)
        self.strat_btn1.configure(background="#C23B22")
        self.strat_btn1.configure(borderwidth=0)
        self.strat_btn1.configure(highlightbackground="#C23B22")
        self.strat_btn1.configure(highlightcolor="#C23B22")
        self.strat_btn1.configure(font="-family {Orator Std} -size 14 -weight bold")
        self.strat_btn1.select()

        self.strat_btn2 = tk.Radiobutton(self.top)
        self.strat_btn2.pack()
        self.strat_btn2.place(x=30, y=350, height=50, width=200)
        self.strat_btn2.configure(text="STRATEGY_2")
        self.strat_btn2.configure(variable=self._strat)
        self.strat_btn2.configure(value=2)
        self.strat_btn2.configure(background="#C23B22")
        self.strat_btn2.configure(highlightbackground="#C23B22")
        self.strat_btn2.configure(highlightcolor="#C23B22")
        self.strat_btn2.configure(font="-family {Orator Std} -size 14 -weight bold")

        self.strat_btn3 = tk.Radiobutton(self.top)
        self.strat_btn3.pack()
        self.strat_btn3.place(x=30, y=400, height=50, width=200)
        self.strat_btn3.configure(text="STRATEGY_3")
        self.strat_btn3.configure(variable=self._strat)
        self.strat_btn3.configure(value=3)
        self.strat_btn3.configure(background="#C23B22")
        self.strat_btn3.configure(highlightbackground="#C23B22")
        self.strat_btn3.configure(highlightcolor="#C23B22")
        self.strat_btn3.configure(font="-family {Orator Std} -size 14 -weight bold")

        self.bt_quitt = tk.Button(self.top)
        self.bt_quitt.place(x=640, y=20, height=50, width=50)
        self.bt_quitt.configure(relief="flat")
        self.bt_quitt.configure(activebackground="#ED1015")
        photo_location = os.path.join(_location,"./quit_rouge.png")
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.bt_quitt.configure(image=_img1)
        self.bt_quitt.configure(command=self.quitter)

    def quitter(self):
        try:
            app_run_support.com.event_stop.set()
            time.sleep(0.1)
            app_run_support.com.deconnexion()
        except:
            pass
        self.top.destroy()


def start_up():
    app_run_support.main()

if __name__ == '__main__':
    app_run_support.main()




