#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Apr 03, 2024 09:36:28 AM CEST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os
import main_r2t2
import subprocess
from threading import Thread

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = main_r2t2.main_r2t2(_top1)
    root.mainloop()

def run():
    thread_run = Thread(target=to_do, args=("app_run.py",))
    thread_run.start()
    #os.system("python3 app_run.py &")
    #subprocess.run(["python3", "app_run.py"])

def test():
    thread_test = Thread(target=to_do, args=("test2.py",))
    thread_test.start()
    #os.system("python3 test2.py")
    #subprocess.run(["python3", "test2.py"])

def to_do(action):
    os.system("python3 "+ action)

if __name__ == '__main__':
    main_r2t2.start_up()




