#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Apr 03, 2024 09:36:21 AM CEST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import main_r2t2_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black'
_tabfg2 = 'white'
_bgmode = 'light'
_tabbg1 = '#d9d9d9'
_tabbg2 = 'gray40'

class main_r2t2:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("720x460+468+138")
        top.attributes('-fullscreen', True)
        #top.minsize(120, 1)
        #top.maxsize(1540, 845)
        top.resizable(0,  0)
        top.title("Main r2t2 - 2024")
        top.configure(background="#d9d9d9")
        #top.configure(highlightbackground="#d9d9d9")
        #top.configure(highlightcolor="#000000")

        self.top = top

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Label_background = tk.Label(self.top)
        self.Label_background.place(x=0, y=0, height=460, width=720)
        self.Label_background.configure(activebackground="#d9d9d9")
        self.Label_background.configure(activeforeground="black")
        self.Label_background.configure(anchor='w')
        self.Label_background.configure(background="#d9d9d9")
        self.Label_background.configure(compound='left')
        self.Label_background.configure(disabledforeground="#a3a3a3")
        self.Label_background.configure(foreground="#000000")
        self.Label_background.configure(highlightbackground="#d9d9d9")
        self.Label_background.configure(highlightcolor="#000000")
        photo_location = os.path.join(_location,"./th_720x460.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label_background.configure(image=_img0)

        self.bt_test = tk.Button(self.top)
        self.bt_test.place(x=90, y=400, height=50, width=200)
        #self.bt_test.configure(activebackground="#d9d9d9")
        #self.bt_test.configure(activeforeground="white")
        self.bt_test.configure(background="#FF7F27")
        self.bt_test.configure(command=main_r2t2_support.test)
        self.bt_test.configure(disabledforeground="#a3a3a3")
        self.bt_test.configure(font="-family {Courier New} -size 16 -weight bold")
        self.bt_test.configure(foreground="#ffffff")
        #self.bt_test.configure(highlightbackground="#d9d9d9")
        #self.bt_test.configure(highlightcolor="#000000")
        self.bt_test.configure(text="Mode Test")

        self.bt_run = tk.Button(self.top)
        self.bt_run.place(x=430, y=400, height=50, width=200)
        #self.bt_run.configure(activebackground="#d9d9d9")
        self.bt_run.configure(activeforeground="white")
        self.bt_run.configure(background="#3DAD52")
        self.bt_run.configure(command=main_r2t2_support.run)
        self.bt_run.configure(disabledforeground="#a3a3a3")
        self.bt_run.configure(font="-family {Courier New} -size 16 -weight bold")
        self.bt_run.configure(foreground="#ffffff")
        #self.bt_run.configure(highlightbackground="#d9d9d9")
        #self.bt_run.configure(highlightcolor="#000000")
        self.bt_run.configure(text="Mode Run")

        self.bt_quitt = tk.Button(self.top)
        self.bt_quitt.place(x=650, y=20, height=50, width=50)
        self.bt_quitt.configure(relief="flat")
        #self.bt_quitt.configure(activebackground="#ffffff")

        photo_location = os.path.join(_location,"./quit_blanc.png")
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.bt_quitt.configure(image=_img1)
        self.bt_quitt.configure(command=top.destroy)



def start_up():
    main_r2t2_support.main()

if __name__ == '__main__':
    main_r2t2_support.main()




